name: Spawn
version: 1.2
author: Tempoo50
main: de.spawn.main.Spawn

commands:
   SetSpawn:
      description: Setze den Spawnpunkt!
   Spawn:
      description: Teleportiere dich zum Spawn!
